#!/usr/bin/python

import sys
import os
import os.path
import glob
import gfs2tex

if not os.access("examples",os.F_OK):
    os.mkdir("examples")

for start in sys.argv[1:]:
    for root, dirs, files in os.walk(start,topdown=True):
        if not ".xvpics" in root:
            example = gfs2tex.Example(root)
            if not os.access("examples/" + example.path,os.F_OK):
                os.symlink("../" + example.path, "examples/" + example.path)
            example.write(style="examples.css")
