.TH gfs-highlight 1 "July 9, 2008" "" "User Commands"

.SH NAME
gfs-highlight \- syntax highlighting/hypertext linking of Gerris simulation files.

.SH SYNOPSIS
.B gfs-highlight
.RI [OPTIONS] < input.gfs > output.html
.SH DESCRIPTION
This manual page documents briefly the
.B gfs-highlight
command.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-\-title=TITLE
Sets the page title.
.TP
.B \-\-css=FILE
Sets the CSS stylesheet filename.
.TP
.B \-h, \-\-help
Display the help and exit.

.SH AUTHOR
gfs-highlight was written by Stephane Popinet <s.popinet@niwa.co.nz>.
.PP
This manual page was written by Ruben Molina <rmolina@udea.edu.co>,
for the Debian project (but may be used by others).
