.TH gfs2gfs 1 "July 9, 2008" "" "User Commands"

.SH NAME
gfs2gfs \- converts old Gerris simulation files to the current format.

.SH SYNOPSIS
.B gfs2gfs
.RI [OPTIONS] < OLDFILE > NEWFILE
.SH DESCRIPTION
This manual page documents briefly the
.B gfs2gfs
command.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Display the help and exit.

.SH AUTHOR
gfs2gfs was written by Stephane Popinet <s.popinet@niwa.co.nz>.
.PP
This manual page was written by Ruben Molina <rmolina@udea.edu.co>,
for the Debian project (but may be used by others).
