.TH gfsjoin 1 "June 19, 2009" "" "User Commands"

.SH NAME
gfsjoin2D, gfsjoin3D \- joins several parallel Gerris simulation files

.SH SYNOPSIS
.B gfsjoin
[OPTIONS] FILE1 FILE2 ... > JOINED
.SH DESCRIPTION
This manual page documents briefly the
.B gfsjoin
command.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-k, \-\-keep
Keep MPI boundaries.
.TP
.B \-v, \-\-verbose
Display statistics and other info.
.TP
.B \-h, \-\-help
Display the help and exit.

.SH AUTHOR
gfsjoin was written by Stephane Popinet <s.popinet@niwa.co.nz>.
