.TH gfsjoin 1 "August 9, 2008" "" "User Commands"

.SH NAME
gfsjoin \- joins Gerris files.

.SH SYNOPSIS
.B gfsjoin
.RI Simfile Directory Rootname NP Tailname > Joined
.SH DESCRIPTION
This manual page documents briefly the
.B gfsjoin
command.

.SH OPTIONS
Simfile:        Name of the simulation file
Directory:      Directory where results are located
Rootname:       File root name
NP:             Number of processors
Tailname:       File tail name

.SH AUTHOR
gfsjoin was written by Daniel Fuster.
.PP
This manual page was written by Ruben Molina <rmolina@udea.edu.co>,
for the Debian project (but may be used by others).
