.TH ppmcombine 1 "August 9, 2008" "" "User Commands"

.SH NAME
ppmcombine \- combines several PPM files produced by a parallel run of Gerris.

.SH SYNOPSIS
.B ppmcombine
.RI [OPTIONS] KEYWORD < input.gfs > output.html
.SH DESCRIPTION
This manual page documents briefly the
.B ppmcombine
command.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-v, \-\-url=URL
Display statistics and other info
.TP
.B \-h, \-\-help
Display the help and exit.

.SH AUTHOR
ppmcombine was written by Stephane Popinet <s.popinet@niwa.co.nz>.
.PP
This manual page was written by Ruben Molina <rmolina@udea.edu.co>,
for the Debian project (but may be used by others).
