.TH rsurfaceinfo 1 "January 28, 2010" "" "User Commands"

.SH NAME
rsurfaceinfo \- displays info on a Gerris terrain database.

.SH SYNOPSIS
.B rsurfaceinfo
.RI [OPTION]
.RI BASENAME

.SH DESCRIPTION
Display information on a Gerris terrain database.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-d VAL, \-\-depth=VAL
display detailed statistics for levels up to VAL
.TP
.B \-h, \-\-help
Display the help and exit.

.SH AUTHOR
rsurfaceinfo was written by Stephane Popinet <s.popinet@niwa.co.nz>.
